# Generated by Django 5.2.3 on 2025-07-02 14:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('bet_api', '0002_chatmessage'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chatmessage',
            options={},
        ),
    ]
